{% set name = "mf2" %}
{% set version = "2022.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6edab8cf9b10379a6c9b5201a1cae60a23ed997be5e168b5bc32423d087e4f37

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - setuptools
    - numpy
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - mf2
    - mf2.adjustable

about:
  home: https://github.com/sjvrijn/mf2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A collection of analytical benchmark functions in multiple fidelities
  doc_url: https://mf2.readthedocs.io/en/latest/
  dev_url: https://github.com/sjvrijn/mf2

extra:
  recipe-maintainers:
    - sjvrijn
