{% set name = "mf2" %}
{% set version = "2021.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d42866dd232b14ed0b78c02e8a756363ef4348907f525ea6d875628ade6b2fdc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - setuptools
    - numpy
    - python >=3.6

test:
  imports:
    - mf2
    - mf2.adjustable

about:
  home: https://github.com/sjvrijn/mf2
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A collection of analytical benchmark functions in multiple fidelities
  doc_url: https://mf2.readthedocs.io/en/latest/
  dev_url: https://github.com/sjvrijn/mf2

extra:
  recipe-maintainers:
    - sjvrijn
